use_seed: True
seed: 633
num_gpu: 1
# eval config
algorithm_name: active_rag
task: ''
# llm config
llm_mode: HF_Model
llm_path: ./model/Llama3-8B-baseline
dtype: "half"
use_vllm: False
temperature: 0.0
top_p: 1.0
generation_stop: ''
generate_maxlength: 100
# retrieval config
realtime_retrieval: True
retrieval_name: colbert_api
n_docs: 5
passages_max_length: -1
# acrive rag config
max_fianl_answer_length: 300
filter_prob: 0.8
masked_prob: 0.4