use_seed: True
seed: 633
num_gpu: 1
# eval config
eval_datapath: ./data/eval_datasets/popqa_longtail_w_gs.jsonl
task: 'PopQA'
output_dir: ./data/eval_results
# llm config
llm_mode: HF_Model
llm_path: ./model/Llama-2-7b-chat-hf
dtype: "half"
use_vllm: False
temperature: 0.0
top_p: 1.0
generation_stop: ''
generate_maxlength: 100
# retrieval config
realtime_retrieval: True
retrieval_name: colbert_api
index_dbPath: /workspace/raglab-exp/data/retrieval/colbertv2.0_embedding/wiki2023-10samples
text_dbPath: /workspace/raglab-exp/data/retrieval/colbertv2.0_passages/wiki2023-10samples/enwiki-20230401-10samples.tsv
retriever_modelPath: ./model/colbertv2.0
n_docs: 10
passages_max_length: 100
# acrive rag config
max_fianl_answer_length: 300
filter_prob: 0.8
masked_prob: 0.4


