use_seed: True
seed: 633
num_gpu: 1
# eval config
algorithm_name: active_rag
task: ''
# llm config
llm_mode: HF_Model
llm_path: ./model/Llama-2-7b-chat-hf
dtype: "half"
use_vllm: False
temperature: 0.0
top_p: 1.0
generation_stop: ''
generate_maxlength: 100
# retrieval config
realtime_retrieval: True
retrieval_name: contriever
index_dbPath: ./data/retrieval/contriever_embedding/wikipedia_embeddings-debug/*
text_dbPath: ./data/retrieval/contriever_passages/psgs_w100-debug.tsv
retriever_modelPath: ./model/contriever-msmarco
n_docs: 10
nbits: 2
# acrive rag config
max_fianl_answer_length: 300
filter_prob: 0.8
masked_prob: 0.4