# RAG method
rag: dsp

# dataset
task: HotpotQA
# eval_datapath: 

# language model
model_mode: HFModel # OpenAI
llm_path: /home/wyd/raglab-exp/model/Llama-2-7b-hf
llm_api: gpt-3.5-turbo
api_key: sk-tFi5dr7s6tfZM9IA99570920Ea464869A88a3aB77128800b
api_base: https://api.aigcbest.top/v1
# generate parameters
generate_maxlength: 1024
temperature: 0.7
output_dir: /home/zxw/raglab-exp/1-eval_output

# retrieval model
retrieval_url: http://100.124.78.167:3389
# retrieval paramters
passages_per_hop: 2

# dsp paramters
inference_CoT: True
signature_retrieval: True
max_hops: 3
eval_threads: 2

# evaluate parametes
metrics: EM # EM F1