# GPU config
num_gpu: 2
# eval config
eval_datapath: /home/zxw/rag/data/1-self_rag/2-eval_data/popqa_longtail_w_gs.jsonl
task: PopQA
output_dir: /home/zxw/rag/raglab-exp/1-eval_output
# llm config
llm_path: /home/zxw/rag/model/Llama-2-7b-hf
generate_maxlength: 300
use_vllm:
# retrieval common config
retrieval_name: contriever
index_dbPath: /home/zxw/rag/data/2-wikipidia_embedding_debug/*
text_dbPath: /home/zxw/rag/data/2-self_rag-retrieval_passages/psgs_w100.tsv
retriever_modelPath: /home/zxw/rag/model/contriever-msmarco
n_docs: 5
# colbert config
nbits: 2
# contriever config
projection_size: 768
indexing_batch_size: 1000000
n_bits: 8
n_subquantizers: 0
per_gpu_batch_size: 64 #Batch size for question encoding 为什么 question 的时候是 64 维度，可能得看一下论文
question_maxlength: 512 # Maximum number of tokens in a question
# self rag 
download_dir: ".cache"
world_size: 1
dtype: "half"
threshold: 0.2  
use_seqscore: 
use_groundness: 
use_utility: 
beam_width: 2
max_depth: 2
w_rel: 1.0
w_sup: 1.0
w_use: 1.0
retrieval_mode: "adaptive_retrieval"


