use_seed: True
seed: 633
num_gpu: 1
# eval config
algorithm_name: iter_retgen
task: Factscore
eval_datapath: ./data/eval_datasets/Factscore/factscore_unlabeled_alpaca_13b_retrieval_without_idx62.jsonl
output_dir: ./data/eval_results
# llm config
llm_mode: HF_Model
llm_path: ./model/Meta-Llama-3-8B-Instruct
dtype: "half"
use_vllm: True
temperature: 0.0
top_p: 1.0
generation_stop: ''
generate_maxlength: 300
# retrieval config
realtime_retrieval: True
retrieval_name: colbert_api

n_docs: 5
passages_max_length: -1
# iterative rag config
max_iteration: 3
