use_seed: True
seed: 633
# GPU config
num_gpu: 1
# eval config
algorithm_name: selfrag_original
eval_datapath: ./data/eval_datasets/ASQA/asqa_eval_gtr_top100.json
task: ASQA
output_dir: ./1-eval_output/
# llm config
llm_mode: HF_Model
llm_path: ./model/selfrag_llama2_7b/
dtype: "half"
use_vllm: True
temperature: 0.0
top_p: 1.0
generation_stop: ''
generate_maxlength: 300 # diff: selfrag_oragnal set 300, but set 100 in selfrag_reproduction base on paper(https://arxiv.org/abs/2310.11511)
# retrieval common config
n_docs: 5
# self rag 
world_size: 1
threshold: 0.2
use_seqscore: True
use_groundness: True
use_utility: True
beam_width: 2
max_depth: 7
w_rel: 1.0
w_sup: 1.0
w_use: 0.5
retrieval_mode: "always_retrieval"
show_specialtokens: True
inference_form: 'long_form'
ignore_cont: False
use_citation: True