use_seed: True
seed: 633
num_gpu: 1
# eval config
algorithm_name: query_rewrite_rag
task: 2WikiMultiHopQA
eval_datapath: ./data/eval_datasets/2WikiMultiHopQA/dev_first_500_samples.jsonl
output_dir: ./data/eval_results/
# llm config
llm_mode: Lora_Model
llm_path: ./model/Llama3-70B-baseline-adapter
basemodel_path: ./model/Meta-Llama-3-70B
quantization: 4bit
dtype: "half"
use_vllm: True
temperature: 0.0
top_p: 1.0
generation_stop: '**'
generate_maxlength: 100
# retrieval config
realtime_retrieval: True
retrieval_name: colbert_api
n_docs: 10
passages_max_length: -1
# max length should bigger than the length of input_ids