use_seed: True
seed: 633
num_gpu: 1
output_dir: ./1-eval_output
task: PopQA
llm_path: ./model/Llama-2-7b-chat-hf
# retrieval config
# retrieval_name: colbert
# index_dbPath: /home/wyd/raglab-exp/data/retrieval/colbertv2.0_embedding
# text_dbPath: ./data/retrieval/colbertv2.0_passages/lotte/lifestyle/dev/collection.tsv
# eval_datapath: ./data/eval_datasets/popqa_longtail_w_gs.jsonl
# retriever_modelPath: ./model/colbertv2.0
# retrieval common config
realtime_retrieval: True
retrieval_name: contriever
index_dbPath: ./data/retrieval/contriever_embedding/wikipedia_embeddings/*
text_dbPath: ./data/retrieval/contriever_passages/psgs_w100.tsv
retriever_modelPath: ./model/contriever-msmarco
n_docs: 10
generate_maxlength: 300
# max length should bigger than the length of input_ids
use_vllm: True
nbits: 2