use_seed: True
seed: 633
num_gpu: 1
output_dir: ./1-eval_output
task: ''
# llm config
llm_path: ./model/Llama-2-7b-hf
use_vllm: True
temperature: 0.0
top_p: 1.0
generation_stop: ''
generate_maxlength: 300
# retrieval config
retrieval_name: colbert
index_dbPath: /home/wyd/raglab-exp/data/retrieval/colbertv2.0_embedding
text_dbPath: ./data/retrieval/colbertv2.0_passages/lotte/lifestyle/dev/collection.tsv
eval_datapath: ''
retriever_modelPath: ./model/colbertv2.0
n_docs: 2
nbits: 2