port: 8893
index_dbPath: /workspace/raglab-exp/data/retrieval/colbertv2.0_embedding/wiki2023
text_dbPath: /workspace/raglab-exp/data/retrieval/colbertv2.0_passages/wiki2023/enwiki-20230401.tsv
retriever_modelPath: ./model/colbertv2.0
