
use_seed: True
seed: 633
num_gpu: 1
# eval config
algorithm_name: dsp
task: HotPotQA
eval_datapath: ./data/eval_datasets/HotPotQA/hotpot_dev_fullwiki_v1.json
# dsp config
eval_train_datapath: ./data/eval_datasets/HotPotQA/hotpot_train_v1.1.json
# language model
model_mode: OpenAI # HFModel # OpenAI
llm_path: ./model/Llama-2-7b-hf
llm_api: gpt-3.5-turbo
api_key: sk-tFi5dr7s6tfZM9IA99570920Ea464869A88a3aB77128800b
api_base: https://api.aigcbest.top/v1
# generate parameters
generate_maxlength: 1024
temperature: 0.7
output_dir: /home/zxw/raglab-exp/1-eval_output

# # retrieval model
# retrieval_url: http://20.102.90.50:2017/wiki17_abstracts
# # retrieval paramters
# passages_per_hop: 2

# retrieval model
realtime_retrieval: True
retrieval_name: contriever
index_dbPath: ./data/retrieval/contriever_embedding/wikipedia_embeddings-debug/*
text_dbPath: ./data/retrieval/contriever_passages/psgs_w100-debug.tsv
retriever_modelPath: ./model/contriever-msmarco
n_docs: 2
nbits: 2
# dsp paramters
inference_CoT: False
signature_retrieval: True
# inference_CoT signature_retrieval function
#     False            False        Generate as llm
#     True             False        Generate as llm with chain-of-thought
#     False            True         Generate as RAG
#     True             True         Generate as RAG with chain-of-thought
max_hops: 3
eval_threads: 1
# evaluate parametes
metrics: EM # EM F1