
use_seed: True
seed: 633
num_gpu: 1
# eval config
algorithm_name: dsp
task: HotPotQA
eval_datapath: ./data/eval_datasets/HotPotQA/hotpot_dev_fullwiki_v1.json
# dsp config
eval_train_datapath: ./data/eval_datasets/HotPotQA/hotpot_train_v1.1.json
# language model
model_mode: HFModel # HFModel # OpenAI
llm_path: ./model/Llama-2-7b-hf
# generate parameters
generate_maxlength: 500
temperature: 0.0
output_dir: /home/zxw/raglab-exp/1-eval_output
# retrieval model
realtime_retrieval: True
retrieval_name: colbert
index_dbPath: /home/wyd/raglab-exp/data/retrieval/colbertv2.0_embedding
text_dbPath: /home/wyd/raglab-exp/data/retrieval/colbertv2.0_passages/lotte/lifestyle/dev/collection.tsv
retriever_modelPath: ./model/colbertv2.0
n_docs: 10
nbits: 2
# dsp paramters
inference_CoT: False
signature_retrieval: True
# inference_CoT signature_retrieval function
#     False            False        Generate as llm
#     True             False        Generate as llm with chain-of-thought
#     False            True         Generate as RAG
#     True             True         Generate as RAG with chain-of-thought
max_hops: 2
eval_threads: 1