use_seed: True
seed: 633
num_gpu: 1
# eval config
algorithm_name: dsp
task: ''
# llm config
llm_path: ./model/Llama-2-7b-hf
dtype: half
use_vllm: False
temperature: 0.0
top_p: 1.0
# api config
model_mode: OpenAI # HFModel # OpenAI
llm_api: gpt-3.5-turbo
api_key: sk-tFi5dr7s6tfZM9IA99570920Ea464869A88a3aB77128800b
api_base: https://api.aigcbest.top/v1
# generate parameters
generate_maxlength: 500

# retrieval model
realtime_retrieval: True
retrieval_name: colbert
index_dbPath: /home/wyd/raglab-exp/data/retrieval/colbertv2.0_embedding
text_dbPath: /home/wyd/raglab-exp/data/retrieval/colbertv2.0_passages/lotte/lifestyle/dev/collection.tsv
retriever_modelPath: ./model/colbertv2.0
n_docs: 10
nbits: 2
# dsp paramters
inference_CoT: False
signature_retrieval: True
# inference_CoT signature_retrieval function
#     False            False        Generate as llm
#     True             False        Generate as llm with chain-of-thought
#     False            True         Generate as RAG
#     True             True         Generate as RAG with chain-of-thought
max_hops: 2
eval_threads: 1