use_seed: True
seed: 633
# GPU config
num_gpu: 2
# eval config
algorithm_name: selfrag_reproduction
eval_datapath: ./data/eval_datasets/PopQA/popqa_longtail_w_gs-10samples.jsonl
task: PopQA
output_dir: ./1-eval_output/
# llm config
llm_mode: HF_Model
llm_path: ./model/selfrag_llama2_7b
dtype: "half"
generate_maxlength: 100
use_vllm: True
temperature: 0.0
top_p: 1.0
generation_stop: ''
# retrieval common config
realtime_retrieval: True
retrieval_name: colbert
index_dbPath: /workspace/raglab-exp/data/retrieval/colbertv2.0_embedding/wiki2023-10samples
text_dbPath: /workspace/raglab-exp/data/retrieval/colbertv2.0_passages/wiki2023-10samples/enwiki-20230401-10samples.tsv

retriever_modelPath: ./model/colbertv2.0
n_docs: 10
passages_max_length: 100
# self rag configs
  # decoding args
threshold: 0.2  
use_seqscore: True
use_groundness: True
use_utility: True
beam_width: 2
max_depth: 7
w_rel: 1.0
w_sup: 1.0
w_use: 0.5
  # inference mode
inference_form: 'short_form'
retrieval_mode: "always_retrieval"
show_specialtokens: True
ignore_cont: False
use_citation: True


