use_seed: True
seed: 633
# GPU config
num_gpu: 2
# eval config
eval_datapath: ./data/eval_datasets/arc_challenge_processed.jsonl
task: ArcChallenge
output_dir: ./1-eval_output/
# llm config
llm_path: ./model/selfrag_llama2_7b
dtype: "half"
generate_maxlength: 50
use_vllm: True
temperature: 0.0
top_p: 1.0
generation_stop: ''
# retrieval common config
realtime_retrieval: True
retrieval_name: contriever
index_dbPath: ./data/retrieval/contriever_embedding/wikipedia_embeddings/*
text_dbPath: ./data/retrieval/contriever_passages/psgs_w100.tsv
retriever_modelPath: ./model/contriever-msmarco
n_docs: 10
# colbert configs 
nbits: 2
# contriever configs
projection_size: 768
indexing_batch_size: 1000000
n_bits: 8
n_subquantizers: 0
per_gpu_batch_size: 64 #Batch size for question encoding 为什么 question 的时候是 64 维度，可能得看一下论文
question_maxlength: 512 # Maximum number of tokens in a question
# self rag configs
download_dir: ".cache"
world_size: 1
  # decoding args
threshold: 0.2
use_seqscore: True
use_groundness: True
use_utility: True
beam_width: 2
max_depth: 7
w_rel: 1.0
w_sup: 1.0
w_use: 0.5
  # inference mode
inference_form: 'short_form'
retrieval_mode: "always_retrieval"
show_specialtokens: True
ignore_cont: False
use_citation: True


