use_seed: True
seed: 633
num_gpu: 2
# eval config
algorithm_name: selfrag_reproduction
task: ''
# llm config
llm_path: ./model/selfrag_llama2_7b/
dtype: "half"
generate_maxlength: 500
use_vllm: True
temperature: 0.0
top_p: 1.0
generation_stop: ''
# retrieval common config
realtime_retrieval: True
retrieval_name: contriever
index_dbPath: ./data/retrieval/contriever_embedding/wikipedia_embeddings-debug/*
text_dbPath: ./data/retrieval/contriever_passages/psgs_w100-debug.tsv
retriever_modelPath: ./model/contriever-msmarco
n_docs: 5
# self rag 
world_size: 1
  # decoding config
threshold: 0.5
use_seqscore: True
use_groundness: True
use_utility: True
beam_width: 2
max_depth: 7
w_rel: 1.0
w_sup: 1.0
w_use: 0.5
  # mode config
inference_form: 'long_form'
retrieval_mode: "adaptive_retrieval"
show_specialtokens: True
ignore_cont: False
use_citation: True