use_seed: True
seed: 633
# GPU config
num_gpu: 1
# eval config
algorithm_name: selfrag_reproduction
eval_datapath: ./data/eval_datasets/ASQA/asqa_eval_gtr_top100.json
task: ASQA
output_dir: ./data/eval_results/
# llm config
llm_mode: HF_Model
llm_path: ./model/selfrag_llama3_8b
dtype: "half"
generate_maxlength: 300
use_vllm: True
temperature: 0.0
top_p: 1.0
generation_stop: ''
# retrieval common config
realtime_retrieval: True
retrieval_name: colbert_api

retriever_modelPath: ./model/colbertv2.0
n_docs: 5
passages_max_length: 100
# self rag configs
threshold: 0.2
use_seqscore: True
use_groundness: True
use_utility: True
beam_width: 2
max_depth: 7
w_rel: 1.0
w_sup: 1.0
w_use: 0.5
  # inference mode
inference_form: 'long_form'
retrieval_mode: "no_retrieval"
show_specialtokens: True
ignore_cont: False
use_citation: True


