use_seed: True
seed: 633
num_gpu: 1
# eval config
algorithm_name: naive_rag
task: ''
# llm config
llm_mode: Lora_Model
llm_path: ./model/Llama3-70B-baseline-adapter
basemodel_path: ./model/Meta-Llama-3-70B
quantization: 4bit
quantization: None
dtype: half
use_vllm: False
temperature: 0.0
top_p: 1.0
generation_stop: ''
generate_maxlength: 300
# retrieval config
realtime_retrieval: False