use_seed: True
seed: 633
num_gpu: 1
# eval config
algorithm_name: naive_rag
eval_datapath: ./data/eval_datasets/2WikiMultiHopQA/dev_first_500_samples.jsonl
task: 2WikiMultiHopQA
output_dir: ./data/eval_results/
# llm config
llm_mode: HF_Model
llm_path: ./model/Llama3-8B-Instruct-baseline
use_vllm: True
temperature: 0.0
top_p: 1.0
generation_stop: ''
generate_maxlength: 300
# retrieval config
realtime_retrieval: False