use_seed: True
seed: 633
num_gpu: 1
# eval config
algorithm_name: naive_rag
task: Factscore
eval_datapath: ./data/eval_datasets/Factscore/factscore_unlabeled_alpaca_13b_retrieval_without_idx62.jsonl
output_dir: ./1-eval_output/
# llm config
llm_mode: HF_Model
llm_path: ./model/Llama-2-7b-chat-hf
use_vllm: True
temperature: 0.0
top_p: 1.0
generation_stop: ''
generate_maxlength: 300
# retrieval config
realtime_retrieval: False
n_docs: 10
passages_max_length: 100