# sh ./run/rag_inference/naive_rag/naive_rag-StrategyQA-Chatgpt-without_retrieval.sh
# sh ./run/rag_inference/naive_rag/naive_rag-WikiMultiQA-Chatgpt.sh
# sh ./run/rag_inference/naive_rag/naive_rag-WikiMultiQA-Chatgpt-without_retrieval.sh
# sh ./run/rag_inference/naive_rag/naive_rag-TriviaQA-Chatgpt.sh
# sh ./run/rag_inference/naive_rag/naive_rag-TriviaQA-Chatgpt-without_retrieval.sh
# sh ./run/rag_inference/naive_rag/naive_rag-StrategyQA-Chatgpt-baseline.sh
# sh ./run/rag_inference/naive_rag/naive_rag-PubHealth-Chatgpt.sh
# sh ./run/rag_inference/naive_rag/naive_rag-PubHealth-Chatgpt-without_retrieval.sh
# sh ./run/rag_inference/naive_rag/naive_rag-PopQA-Chatgpt.sh
# sh ./run/rag_inference/naive_rag/naive_rag-HotPotQA-Chatgpt.sh
# sh ./run/rag_inference/naive_rag/naive_rag-PopQA-Chatgpt-without_retrieval.sh
# sh ./run/rag_inference/naive_rag/naive_rag-HotPotQA-Chatgpt-without_retrieval.sh
# sh ./run/rag_inference/naive_rag/naive_rag-Feverous-Chatgpt.sh
# sh ./run/rag_inference/naive_rag/naive_rag-Feverous-Chatgpt-without_retrieval.sh
# sh ./run/rag_inference/naive_rag/naive_rag-Factscore-Chatgpt.sh
# sh ./run/rag_inference/naive_rag/naive_rag-Factscore-Chatgpt-without_retrieval.sh
# sh ./run/rag_inference/naive_rag/naive_rag-ASQA-Chatgpt.sh
# sh ./run/rag_inference/naive_rag/naive_rag-ASQA-Chatgpt-without_retrieval.sh
# sh ./run/rag_inference/naive_rag/naive_rag-ArcChallenge-Chatgpt.sh
# sh ./run/rag_inference/naive_rag/naive_rag-ArcChallenge-Chatgpt-without_retrieval.sh
# sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-WikiMultiQA-Chatgpt.sh
# sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-TriviaQA-Chatgpt.sh
# sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-StrategyQA-Chatgpt.sh
# sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-PubHealth-Chatgpt.sh
# sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-PopQA-Chatgpt.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-HotPotQA-Chatgpt.sh
# sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-Feverous-Chatgpt.sh
# sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-Factscore-Chatgpt.sh
# sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-ASQA-Chatgpt.sh
# sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-ArcChallenge-Chatgpt.sh
# sh ./run/rag_inference/iterative_rag/iterative_rag-WikiMultiHopQA-Chatgpt-maxiter_3.sh
# sh ./run/rag_inference/iterative_rag/iterative_rag-TriviaQA-Chatgpt-maxiter_3.sh
# sh ./run/rag_inference/iterative_rag/iterative_rag-StrategyQA-Chatgpt-maxiter_3.sh
# sh ./run/rag_inference/iterative_rag/iterative_rag-PubHealth-Chatgpt-maxiter_3.sh
# sh ./run/rag_inference/iterative_rag/iterative_rag-PopQA-Chatgpt-maxiter_3.sh
# sh ./run/rag_inference/iterative_rag/iterative_rag-HotPotQA-Chatgpt-maxiter_3.sh
# sh ./run/rag_inference/iterative_rag/iterative_rag-Feverous-Chatgpt-maxiter_3.sh
# sh ./run/rag_inference/iterative_rag/iterative_rag-Factscore-Chatgpt-maxiter_3.sh
# sh ./run/rag_inference/iterative_rag/iterative_rag-ASQA-Chatgpt-maxiter_3.sh
# sh ./run/rag_inference/iterative_rag/iterative_rag-ArcChallenge-Chatgpt-maxiter_3.sh
# sh ./run/rag_inference/self_ask/self_ask-WikiMultiHopQA-Chatgpt.sh
# sh ./run/rag_inference/self_ask/self_ask-TriviaQA-Chatgpt.sh
# sh ./run/rag_inference/self_ask/self_ask-StrategyQA-Chatgpt.sh
# sh ./run/rag_inference/self_ask/self_ask-PubHealth-Chatgpt.sh
# sh ./run/rag_inference/self_ask/self_ask-PopQA-Chatgpt.sh
# sh ./run/rag_inference/self_ask/self_ask-HotPotQA-Chatgpt.sh
# sh ./run/rag_inference/self_ask/self_ask-Feverous-Chatgpt.sh
# sh ./run/rag_inference/self_ask/self_ask-Factscore-Chatgpt.sh
# sh ./run/rag_inference/self_ask/self_ask-ASQA-Chatgpt.sh
# sh ./run/rag_inference/self_ask/self_ask-ArcChallenge-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-WikiMultiHopQA-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-TriviaQA-Chatgpt.sh
# sh ./run/rag_inference/active_rag/active_rag-StrategyQA-Chatgpt.sh
# sh ./run/rag_inference/active_rag/active_rag-PubHealth-Chatgpt.sh
# sh ./run/rag_inference/active_rag/active_rag-PopQA-Chatgpt.sh
# sh ./run/rag_inference/active_rag/active_rag-HotPotQA-Chatgpt.sh
# sh ./run/rag_inference/active_rag/active_rag-Feverous-Chatgpt.sh
# sh ./run/rag_inference/active_rag/active_rag-Factscore-Chatgpt.sh
# sh ./run/rag_inference/active_rag/active_rag-ASQA-Chatgpt.sh
# sh ./run/rag_inference/active_rag/active_rag-ArcChallenge-Chatgpt.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-ArcChallenge-no_retrieval-pregiven_passages.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-ArcChallenge-always_retrieval-pregiven_passages.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-ArcChallenge-adaptive_retrieval-pregiven_passages.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PubHealth-no_retrieval-pregiven_passages.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PubHealth-always_retrieval-pregiven_passages.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PubHealth-adaptive_retrieval-pregiven_passages.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PopQA-adaptive_retrieval-pregiven_passages.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PopQA-no_retrieval-pregiven_passages.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PopQA-always_retrieval-pregiven_passages.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-Feverous-no_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-Feverous-always_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-Feverous-adaptive_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-StrategyQA-no_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-StrategyQA-always_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-StrategyQA-adaptive_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-HotPotQA-no_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-HotPotQA-always_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-HotPotQA-adaptive_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-long_form-Factscore-no_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-long_form-ASQA-no_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-long_form-Factscore-always_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-long_form-Factscore-adaptive_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-WikiMultiHopQA-no_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-WikiMultiHopQA-adaptive_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-WikiMultiHopQA-always_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-TriviaQA-no_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-TriviaQA-always_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-TriviaQA-adaptive_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PubHealth-no_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PubHealth-always_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PubHealth-adaptive_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PopQA-no_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PopQA-always_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-PopQA-adaptive_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-ArcChallenge-no_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-ArcChallenge-always_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-short_form-ArcChallenge-adaptive_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-long_form-ASQA-always_retrieval.sh
# sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-long_form-ASQA-adaptive_retrieval.sh