sh ./run/rag_inference/naive_rag/naive_rag-PubHealth-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-HotPotQA-Chatgpt-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-PopQA-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-WikiMultiQA-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-Factscore-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-StrategyQA-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-HotPotQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-interact-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-TriviaQA-Chatgpt-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-interact-Llama3-70B-baseline_4bit-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-ArcChallenge-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-ASQA-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-MMLU-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-MMLU-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-WikiMultiQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/naive_rag/naive_rag-MMLU-Llama3-70B-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-ASQA-Chatgpt-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-StrategyQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/naive_rag/naive_rag-Factscore-Chatgpt-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-WikiMultiQA-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-TriviaQA-Chatgpt.sh
sh ./run/rag_inference/naive_rag/naive_rag-interact-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-PopQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/naive_rag/naive_rag-ASQA-Chatgpt.sh
sh ./run/rag_inference/naive_rag/naive_rag-HotPotQA-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-HotPotQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/naive_rag/naive_rag-HotPotQA-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-TriviaQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/naive_rag/naive_rag-interact-openai.sh
sh ./run/rag_inference/naive_rag/naive_rag-TriviaQA-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-MMLU-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-TriviaQA-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-Factscore-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-ArcChallenge-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-ArcChallenge-Llama3-70B-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-WikiMultiQA-Chatgpt-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-StrategyQA-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-PubHealth-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/naive_rag/naive_rag-PopQA-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-PubHealth-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-Factscore-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-StrategyQA-Chatgpt.sh
sh ./run/rag_inference/naive_rag/naive_rag-PubHealth-Chatgpt.sh
sh ./run/rag_inference/naive_rag/naive_rag-HotPotQA-Chatgpt.sh
sh ./run/rag_inference/naive_rag/naive_rag-ASQA-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-ArcChallenge-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-ArcChallenge-Chatgpt-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-PubHealth-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-Factscore-Llama3-70B-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-HotPotQA-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-ArcChallenge-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/naive_rag/naive_rag-PubHealth-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-Factscore-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/naive_rag/naive_rag-StrategyQA-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-MMLU-Chatgpt.sh
sh ./run/rag_inference/naive_rag/naive_rag-ArcChallenge-Chatgpt.sh
sh ./run/rag_inference/naive_rag/naive_rag-ASQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/naive_rag/naive_rag-PopQA-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-ArcChallenge-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-StrategyQA-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-TriviaQA-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-TriviaQA-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-PopQA-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-ASQA-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-ASQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-Factscore-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-interact-Llama3-70B-baseline-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-WikiMultiQA-Llama3-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-MMLU-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-WikiMultiQA-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-MMLU-Chatgpt-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-PopQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-PubHealth-Llama3-70B-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-MMLU-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/naive_rag/naive_rag-Factscore-Chatgpt.sh
sh ./run/rag_inference/naive_rag/naive_rag-HotPotQA-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-interact-Llama3-70B-baseline_4bit-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-PopQA-Chatgpt-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-StrategyQA-Chatgpt-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-PopQA-Chatgpt.sh
sh ./run/rag_inference/naive_rag/naive_rag-ASQA-Llama3-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-TriviaQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-WikiMultiQA-Chatgpt.sh
sh ./run/rag_inference/naive_rag/naive_rag-StrategyQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/naive_rag/naive_rag-PubHealth-Chatgpt-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-interact-Llama3-70B-baseline-without_retrieval.sh
sh ./run/rag_inference/naive_rag/naive_rag-WikiMultiQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-StrategyQA-Llama3-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-WikiMultiQA-Chatgpt.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-Factscore-Llama3-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-PubHealth-Llama3-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-ArcChallenge-Chatgpt.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-PopQA-Llama3-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-PopQA-Chatgpt.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-Factscore-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-ASQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-ArcChallenge-Llama3-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-HotPotQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-PopQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-ArcChallenge-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-PopQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-MMLU-Chatgpt.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-WikiMultiQA-Llama3-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-HotPotQA-Llama3-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-TriviaQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-ArcChallenge-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-interact.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-HotPotQA-Chatgpt.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-PubHealth-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-TriviaQA-Chatgpt.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-PubHealth-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-StrategyQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-ASQA-Llama3-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-StrategyQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-ASQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-PubHealth-Chatgpt.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-Factscore-Chatgpt.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-MMLU-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-Factscore-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-MMLU-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-interact-openai.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-WikiMultiQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-WikiMultiQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-TriviaQA-Llama3-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-StrategyQA-Chatgpt.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-HotPotQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-TriviaQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-MMLU-Llama3-baseline.sh
sh ./run/rag_inference/query_rewrite_rag/query_rewrite_rag-ASQA-Chatgpt.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-ArcChallenge-Llama3-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-PopQA-Llama3-70B-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-ASQA-Llama3-70B-baseline_4bit-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-TriviaQA-Llama3-70B-baseline_4bit-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-Factscore-Llama3-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-PopQA-Llama3-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-ASQA-Llama3-70B-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-MMLU-Chatgpt.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-MMLU-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-ArcChallenge-Llama3-70B-baseline_4bit-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-HotPotQA-Llama3-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-WikiMultiHopQA-Chatgpt-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-Factscore-Llama3-70B-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-TriviaQA-Llama3-70B-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-PopQA-Chatgpt-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-StrategyQA-Chatgpt-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-PopQA-Llama3-70B-baseline_4bit-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-MMLU-Llama3-baseline.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-StrategyQA-Llama3-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-interact-openai.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-ArcChallenge-Llama3-70B-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-Factscore-Llama3-70B-baseline_4bit-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-StrategyQA-Llama3-70B-baseline_4bit-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-MMLU-Llama3-70B-baseline.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-HotPotQA-Llama3-70B-baseline_4bit-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-StrategyQA-Llama3-70B-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-PubHealth-Chatgpt-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-HotPotQA-Chatgpt-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-TriviaQA-Chatgpt-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-TriviaQA-Llama3-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-ArcChallenge-Chatgpt-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-WikiMultiHopQA-Llama3-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-interact.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-PubHealth-Llama3-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-WikiMultiHopQA-Llama3-70B-baseline_4bit-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-PubHealth-Llama3-70B-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-WikiMultiHopQA-Llama3-70B-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-ASQA-Chatgpt-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-HotPotQA-Llama3-70B-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-Factscore-Chatgpt-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-ASQA-Llama3-baseline-maxiter_3.sh
sh ./run/rag_inference/iterative_rag/iterative_rag-PubHealth-Llama3-70B-baseline_4bit-maxiter_3.sh
sh ./run/rag_inference/self_ask/self_ask-PopQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-TriviaQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-interact-openai.sh
sh ./run/rag_inference/self_ask/self_ask-ArcChallenge-Chatgpt.sh
sh ./run/rag_inference/self_ask/self_ask-TriviaQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/self_ask/self_ask-StrategyQA-Llama3-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-StrategyQA-Chatgpt.sh
sh ./run/rag_inference/self_ask/self_ask-ASQA-Llama3-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-PopQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/self_ask/self_ask-StrategyQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-PubHealth-Chatgpt.sh
sh ./run/rag_inference/self_ask/self_ask-MMLU-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/self_ask/self_ask-MMLU-Llama3-70B-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-WikiMultiHopQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/self_ask/self_ask-HotPotQA-Chatgpt.sh
sh ./run/rag_inference/self_ask/self_ask-TriviaQA-Llama3-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-ArcChallenge-Llama3-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-PubHealth-Llama3-70B-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-ArcChallenge-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/self_ask/self_ask-PopQA-Llama3-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-TriviaQA-Chatgpt.sh
sh ./run/rag_inference/self_ask/self_ask-HotPotQA-Llama3-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-Factscore-Llama3-70B-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-ASQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/self_ask/self_ask-MMLU-Chatgpt.sh
sh ./run/rag_inference/self_ask/self_ask-interact.sh
sh ./run/rag_inference/self_ask/self_ask-ASQA-Chatgpt.sh
sh ./run/rag_inference/self_ask/self_ask-ASQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-StrategyQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/self_ask/self_ask-PubHealth-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/self_ask/self_ask-HotPotQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/self_ask/self_ask-HotPotQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-PubHealth-Llama3-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-Factscore-Chatgpt.sh
sh ./run/rag_inference/self_ask/self_ask-Factscore-Llama3-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-Factscore-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/self_ask/self_ask-WikiMultiHopQA-Llama3-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-MMLU-Llama3-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-WikiMultiHopQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-ArcChallenge-Llama3-70B-baseline.sh
sh ./run/rag_inference/self_ask/self_ask-WikiMultiHopQA-Chatgpt.sh
sh ./run/rag_inference/self_ask/self_ask-PopQA-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-ASQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-TriviaQA-Llama3-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-Factscore-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-MMLU-Llama3-70B-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-HotPotQA-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-HotPotQA-Llama3-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-ASQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/active_rag/active_rag-PubHealth-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/active_rag/active_rag-ArcChallenge-Llama3-70B-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-MMLU-Llama3-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-StrategyQA-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-PopQA-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-PubHealth-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-Factscore-Llama3-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-TriviaQA-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-HotPotQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/active_rag/active_rag-PopQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-StrategyQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-ArcChallenge-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-ArcChallenge-Llama3-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-ArcChallenge-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/active_rag/active_rag-interact-openai.sh
sh ./run/rag_inference/active_rag/active_rag-WikiMultiHopQA-Llama3-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-Factscore-Llama3-70B-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-PubHealth-Llama3-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-HotPotQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-ASQA-Llama3-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-Factscore-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/active_rag/active_rag-TriviaQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/active_rag/active_rag-ASQA-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-TriviaQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-PubHealth-Llama3-70B-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-WikiMultiHopQA-Llama3-70B-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-PopQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/active_rag/active_rag-WikiMultiHopQA-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-interact-Llama3.sh
sh ./run/rag_inference/active_rag/active_rag-PopQA-Llama3-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-MMLU-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/active_rag/active_rag-MMLU-Chatgpt.sh
sh ./run/rag_inference/active_rag/active_rag-StrategyQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/active_rag/active_rag-StrategyQA-Llama3-baseline.sh
sh ./run/rag_inference/active_rag/active_rag-WikiMultiHopQA-Llama3-70B-baseline_4bit.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-ArcChallenge-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-interact-short_form-always_retrieval-lora.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-long_form-Factscore-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-WikiMultiHopQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-WikiMultiHopQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-WikiMultiHopQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-TriviaQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-TriviaQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PopQA-adaptive_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-HotPotQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-MMLU-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-long_form-Factscore-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PopQA-no_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-ArcChallenge-no_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PopQA-always_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-long_form-Factscore-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-MMLU-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-StrategyQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PubHealth-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PubHealth-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-MMLU-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-StrategyQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PopQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-ArcChallenge-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PopQA-adaptive_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-WikiMultiHopQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PubHealth-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PopQA-no_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PopQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PopQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-long_form-ASQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PubHealth-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-WikiMultiHopQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PubHealth-adaptive_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PopQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-long_form-ASQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-interact-long_form-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PubHealth-no_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-long_form-ASQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PubHealth-adaptive_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-ArcChallenge-adaptive_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-TriviaQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-ArcChallenge-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-long_form-ASQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-HotPotQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-ArcChallenge-no_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-MMLU-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PubHealth-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-WikiMultiHopQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-StrategyQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-HotPotQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-MMLU-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-StrategyQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-ArcChallenge-always_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-long_form-ASQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-StrategyQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PubHealth-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PopQA-adaptive_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-interact-long_form-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-HotPotQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-ArcChallenge-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-ArcChallenge-always_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-MMLU-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-ArcChallenge-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PubHealth-no_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-ArcChallenge-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-interact-short_form-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PubHealth-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-StrategyQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PubHealth-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PopQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-TriviaQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-ArcChallenge-always_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-long_form-Factscore-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-WikiMultiHopQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-HotPotQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PopQA-always_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-StrategyQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-TriviaQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-long_form-ASQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-interact-short_form-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-MMLU-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PopQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-HotPotQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-ArcChallenge-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PubHealth-always_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PubHealth-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PopQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-TriviaQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-TriviaQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-long_form-Factscore-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-WikiMultiHopQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-TriviaQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-ArcChallenge-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-MMLU-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-ArcChallenge-adaptive_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-long_form-ASQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-MMLU-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-HotPotQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-TriviaQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-HotPotQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-ArcChallenge-adaptive_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PopQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-long_form-Factscore-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-interact-short_form-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-long_form-ASQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-PubHealth-no_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-WikiMultiHopQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-long_form-Factscore-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PubHealth-adaptive_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-ArcChallenge-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-interact-short_form-no_retrieval-lora.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_8B-short_form-StrategyQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PopQA-no_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-HotPotQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-ArcChallenge-no_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-long_form-ASQA-always_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-long_form-Factscore-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-long_form-Factscore-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-PubHealth-always_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PopQA-adaptive_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B-short_form-StrategyQA-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-interact-long_form-no_retrieval.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PubHealth-always_retrieval-pregiven_passages.sh
sh ./run/rag_inference/selfrag_reproduction/selfrag_reproduction-evaluation-selfrag_llama3_70B_4bit-short_form-PopQA-always_retrieval-pregiven_passages.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-Arc-Llama3-baseline.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-interact-Llama3-baseline.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-MMLU-Llama3-baseline.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-WikiMultiQA-Llama3-baseline.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-HotPotQA-Llama3-baseline.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-ASQA-Llama3-baseline.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-TriviaQA-Llama3-baseline.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-Factscore-Llama3-baseline copy.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-StrategyQA-Llama3-baseline.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-PopQA-Llama3-baseline.sh