sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-StrategyQA-Critic_model_2w.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-Factscore-Critic_model_2w.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-PopQA-Critic_model_2w.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-ASQA-Critic_model_2w.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-MMLU-Critic_model_2w.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-HotPotQA-Critic_model_2w.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-Arc-Critic_model_2w.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-WikiMultiQA-Critic_model_2w.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-PubHealth-Critic_model_2w.sh
sh ./run/rag_inference/unified_critic_rag/unified_critic_rag-TriviaQA-Critic_model_2w.sh